### ISSUE TITLE
no image found 

### ISSUE THREAD

**Issue by kavin901020** [karanjakhar/Image-Segmentation#2]
W0714 21:00:39.910784 140687696258816 _internal.py:122]  * Debugger is active!
I0714 21:00:39.918538 140687696258816 _internal.py:122]  * Debugger PIN: 195-256-353
I0714 21:00:57.617755 140685325235968 _internal.py:122] 127.0.0.1 - - [14/Jul/2020 21:00:57] "GET / HTTP/1.1" 200 -
I0714 21:00:57.636082 140685325235968 _internal.py:122] 127.0.0.1 - - [14/Jul/2020 21:00:57] "GET /static/style.css HTTP/1.1" 200 -
I0714 21:00:57.639063 140685325235968 _internal.py:122] 127.0.0.1 - - [14/Jul/2020 21:00:57] "GET /static/bk.jpg HTTP/1.1" 200 -
I0714 21:00:57.752359 140685325235968 _internal.py:122] 127.0.0.1 - - [14/Jul/2020 21:00:57] "GET /favicon.ico HTTP/1.1" 404 -
post here
I0714 21:01:32.372935 140685325235968 _internal.py:122] 127.0.0.1 - - [14/Jul/2020 21:01:32] "POST / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ljs/Image-Segmentation-master/image segmentation.py", line 25, in index
    img.save(path)
  File "/home/ljs/anaconda3/envs/flask/lib/python3.6/site-packages/werkzeug/datastructures.py", line 2799, in save
    dst = open(dst, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/imgseg/2020-07-10 10-49-54屏幕截图.png'
when I run your code, it prints that no image found, but I do have image

**Comment by karanjakhar** [comment]
Please create imgseg/ folder in /tmp folder. Or you can change the saving path.
